# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f3001a852a6281a1068296afc08cb674e3b78ae767421ee45d700760ec6a14822ff5b17bfb3758fa831574e015cbe1b3c1ca2a7831e0cfcb47259f85576977c

test:
  secret_key_base: 7f98662bac06110d8e48d58226ad2ba29f7ab0c9443e20e96726a93df8330a48609784b89c388661b8ad2c520706f6bb2e7cfc8d116187bda088f17f27be814a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
